[package]
name = "serval"
version = "1.1.1"
authors = ["remu <thomas.gadola@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
anyhow = "1.0.31"
rustyline = "6.2.0"

